src/AppBundle/Entity/Checklist.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Checklist
 *
 * @ORM\Table(name="checklist")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ChecklistRepository")
 */
class Checklist
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="service_id", type="integer")
     */
    private $serviceId;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="file", type="string", length=255, nullable=true)
     */
    private $file;

    /**
     * @ORM\ManyToOne(targetEntity="Service", inversedBy="checklists")
     * @ORM\JoinColumn(name="service_id", referencedColumnName="id")
     */
    private $service;

    /**
     * @ORM\OneToMany(targetEntity="ChecklistItem", mappedBy="checklist")
     */
    private $items;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set serviceId
     *
     * @param integer $serviceId
     *
     * @return Checklist
     */
    public function setServiceId($serviceId)
    {
        $this->serviceId = $serviceId;

        return $this;
    }

    /**
     * Get serviceId
     *
     * @return int
     */
    public function getServiceId()
    {
        return $this->serviceId;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Checklist
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set file
     *
     * @param string $file
     *
     * @return Checklist
     */
    public function setFile($file)
    {
        $this->file = $file;

        return $this;
    }

    /**
     * Get file
     *
     * @return string
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Get items
     *
     * @return ChecklistItem[]
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Get service
     *
     * @return Service
     */
    public function getService()
    {
        return $this->service;
    }
}

src/AppBundle/Entity/Service.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Service
 *
 * @ORM\Table(name="service")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ServiceRepository")
 */
class Service
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="url_name", type="string", length=50, unique=true)
     */
    private $urlName;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="ServicePackage", mappedBy="service")
     */
    private $packages;

    /**
     * @ORM\OneToMany(targetEntity="Checklist", mappedBy="service")
     */
    private $checklists;

    /**
     * @var string
     *
     * @ORM\Column(name="lead_text", type="text")
     */
    private $leadText;

    public function getLeadText()
    {
        return $this->leadText;
    }

    public function getPackages()
    {
        return $this->packages;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Service
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set urlName
     *
     * @param string $urlName
     *
     * @return Service
     */
    public function setUrlName($urlName)
    {
        $this->urlName = $urlName;

        return $this;
    }

    /**
     * Get urlName
     *
     * @return string
     */
    public function getUrlName()
    {
        return $this->urlName;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Service
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    public function getlowestPrice()
    {
        return $this->getPackages()[0]->getPrice();
    }

    public function getFees()
    {
        return $this->getPackages()[0]->getFees();
    }

    public function getFeesIncluded()
    {
        return $this->getPackages()[0]->getFeesIncluded();
    }
}

src/AppBundle/Controller/ChecklistController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Checklist;
use AppBundle\Entity\ChecklistItem;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * Class ChecklistController
 * @package AppBundle\Controller
 * @Route("/checklisten")
 */
class ChecklistController extends Controller
{
    /**
     * @Route("/")
     */
    public function showChecklistsOverviewAction()
    {
        $checklists = $this->getDoctrine()
            ->getRepository('AppBundle:Checklist')
            ->findAll();

        return $this->render('@App/Checklist/show_checklists.html.twig', array(
            'checklists' => $checklists
        ));
    }

    /**
     * @Route("/{serviceUrl}", name="checklist_service")
     */
    public function showChecklistAction($serviceUrl)
    {
        /** @var Service $service */
        if (!$service = $this->getDoctrine()
            ->getRepository('AppBundle:Service')
            ->findOneBy(array('urlName' => $serviceUrl))
        ) {
            throw $this->createNotFoundException('Der Service wurde nicht gefunden!');
        }
        /** @var Checklist $checklist */
        if (!$checklists = $this->getDoctrine()
            ->getRepository('AppBundle:Checklist')
            ->findBy(array('serviceId' => $service->getId()))
        ) {
            throw $this->createNotFoundException('Die Checkliste wurden nicht gefunden!');
        }

        return $this->render('@App/Checklist/show_checklist.html.twig', array(
            'service' => $service,
            'checklists' => $checklists,
        ));
    }

}

src/AppBundle/Resources/views/Checklist/show_checklist.html.twig
{% extends "::base.html.twig" %}

{% block javascripts %}
    <script type="text/javascript">
        $('[data-toggle="popover"]').popover();
        $('[data-toggle="popover"]').on('click', function (e) {
            $('[data-toggle="popover"]').not(this).popover('hide');
        });
        var selectChecklist = function () {
            var checklistId = $('#checklistSelector').val();
            showOne(checklistId);
        };

        function showOne(id) {
            console.log(id);
            {% for checklist in checklists %}
            $('#checklist' + {{ checklist.id }}).hide();
            {% endfor %}
            $('#checklist' + id).show();
        }
    </script>
{% endblock %}

{% block body %}
<section class="section section-colored">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2>Checkliste {{ service.name }}</h2>
                {% if checklists | length > 1 %}
                    <p class="lead">In den folgenden Checklisten führen wir auf, welche Unterlagen für den Behördengang benötigt werden:</p>
                {% else %}
                    <p class="lead">In der folgenden Checkliste führen wir auf, welche Unterlagen für den Behördengang benötigt werden:</p>
                {% endif %}
                {% if checklists | length > 1 %}
                        <div class="input-group">
                            <div class="form-group">
                                <label for="checklistSelector" class="control-label">Checklisten</label>
                                <select id="checklistSelector" class="form-control" onchange="selectChecklist()">
                                    {% for key, checklist in checklists %}
                                        <option value="{{ checklist.id }}" {% if key == 0 %}selected{% endif %}>{{ checklist.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                {% endif %}
                <br>
                {% for key, checklist in checklists %}
                <div class="row checklists" id="checklist{{ checklist.id }}" {% if key != 0 %}style="display: none;"{% endif %}>
                    {% for item in checklist.items %}
                    <div class="panel">
                        <div class="panel-body">
                            <div class="col-md-10">
                                <h4 class="">{{ item.title }}</h4>
                                {% if item.info is not null %}
                                    <p class="">({{ item.info }})</p>
                                {% endif %}
                            </div>
                            {% if item.tooltip %}
                                <button type="button" class="btn btn-primary btn-lg col-md-2 popoverBtn" data-container="body" data-toggle="popover" data-placement="left"
                                        title="{{ item.title }}"
                                        data-content="{{ item.tooltip | raw }}">
                                    Details
                                </button>
                            {% endif %}
                            {% if item.file %}
                                <a type="button" class="btn btn-primary btn-lg col-md-2" target="_blank"
                                   href="/files/checklist/{{ item.file }}"
                                >
                                    Download
                                </a>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
                <br><br>
                <p class="lead text-center">Gerne übernehmen wir diesen Behördengang für Sie: <a href="/service/{{ service.urlName }}">Weitere Informationen</a></p>
            </div>
        </div>
    </div>
</section>
    <section class="section section-callToAction">
        <div class="container">
            <div style="padding-top: 60px; padding-bottom: 60px;">
                <div class="row">
                    <div class="col-md-12">
                        <div class="container">
                            <div class="col-md-4 text-center">
                                <div class="text-right">
                                    <img src="/images/curved-next-arrow.svg" style="height:60px;" class="hidden-xs hidden-sm">
                                </div>
                                <div class="hidden-xs hidden-sm">
                                    <p class="text-left lead hidden-xs">
                                        <strong>Expressauftrag</strong> erteilen:
                                        <br>
                                        Erledigt am nächsten Arbeitstag
                                    </p>
                                </div>
                                <div class="visible-xs visible-sm">
                                    <p class="text-center lead visible-xs">
                                        <strong>Expressauftrag</strong> erteilen:
                                        <br>
                                        Erledigt am nächsten Arbeitstag
                                    </p>
                                </div>
                            </div>
                            <div class="col-md-4 text-center">
                                <a
                                        id="headerSelectorBtn"
                                        class="btn btn-success btn-lg"
                                        type="button"
                                        href="/warenkorb/{{ service.urlName }}"
                                        style="font-size: 25px; white-space: normal ">
                                    Jetzt online beauftragen
                                </a>
                            </div>
                            <div class="col-md-4">
                                <img src="/images/curved-next-arrow.svg" style="height:60px; transform: scaleX(-1);" class="hidden-xs hidden-sm">
                                <div class="hidden-xs hidden-sm">
                                    <p class="text-right lead">
                                        Regulärer Preis: <del>{{ (service.lowestPrice) + 10 }},00€</del><br>
                                        <strong>Neukunden Aktion: {{ service.lowestPrice | replace({'.': ','}) }}€</strong><br>
                                        {% if service.feesIncluded %}
                                            <small><i>(Inkl. aller Amtsgebühren{% if service.fees is not null %} <br>ca. {{ service.fees | replace({'.': ','}) }}€{% endif %})</i></small>
                                        {% endif %}
                                        <br>
                                    </p>
                                </div>
                                <div class="visible-xs visible-sm">
                                    <p class="text-center lead"><br>
                                        Regulärer Preis: <del>{{ (service.lowestPrice) + 10 }},00€</del><br>
                                        <strong>Neukunden Aktion: {{ service.lowestPrice | replace({'.': ','}) }}€</strong><br>
                                        {% if service.feesIncluded %}
                                            <small><i>(Inkl. aller Amtsgebühren{% if service.fees is not null %} <br>ca. {{ service.fees | replace({'.': ','}) }}€{% endif %})</i></small>
                                        {% endif %}
                                        <br>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/AppBundle/Resources/views/Checklist/show_checklists.html.twig
{% extends "::base.html.twig" %}

{% block body %}
<section class="section section-colored">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2>Checklisten</h2>
                <p class="lead">Welche Unterlagen werden für welchen Behördengang benötigt? Im folgenden haben wir Checklisten für Sie zusammengestellt, in denen Sie alle notwendigen Unterlagen finden</p>
                <br>
                <div class="row">
                    {% for key, checklist in checklists %}
                    <div class="panel">
                        <div class="panel-body">
                            <a href="/checklisten/{{ checklist.service.urlName }}"><div class="col-md-10">
                                <h4 class="">{{ checklist.name }}</h4>
                                </div></a>
                            {% if checklist.file %}
                                <a type="button" class="btn btn-primary btn-lg col-md-2" target="_blank"
                                   href="/files/checklist/{{ item.file }}"
                                >
                                    Download PDF
                                </a>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}